name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible and SSH dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible sshpass

      - name: Deploy using Ansible
        env:
          VM_IP: ${{ secrets.VM_IP_ADDRESS }}  
          VM_USER: ${{ secrets.VM_USERNAME }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }}  
        run: |
          ansible-playbook -i "${{secrets.VM_IP_ADDRESS}}," playbook.yml -u "azureuser" \
            --extra-vars "ansible_ssh_pass=${{ secrets.VM_PASSWORD }}" \
            -e 'ansible_ssh_common_args="-o StrictHostKeyChecking=no"'
